disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Haruki's Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[params.author]
name = "Haruki Kubota"
headline = "Programmer | Aspiring Pilots"
bio = ""
links = [
    { github = "https://github.com/kuboshiba" },
]
