disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 1
title = "Haruki's Blog"

[params]
displayName = "JA"
isoCode = "ja"
rtl = false
dateFormat = "2006年1月2日"

[params.author]
name = "Haruki Kubota"
headline = "Software Engineer | Aspiring Pilots"
bio = "Software Engineer | Aspiring Pilots"
links = [
    { github = "https://github.com/kuboshiba" },
]
image = "img/icon.jpeg"
