[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "7ifD5vExnZ"
weight = 9999

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "3I8dM350GA"
weight = 9999

[[footer]]
none = "none"
