[[main]]
none = "none"

[[main]]
name = "Home"
pageRef = "/"
identifier = "iWit3D003f"
weight = 1

[[main]]
name = "About"
pageRef = "about"
identifier = "7ifD5vExnZ"
weight = 2

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "3I8dM350GA"
weight = 3

[[footer]]
none = "none"
